sudo: false
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
env:
  matrix:
  - TOXENV=qa
  - DJANGO=18
  - DJANGO=19
  - DJANGO=110
  - DJANGO=111
install:
  - pip install tox
script:
- |
  if [[ -z $DJANGO ]]; then
    tox -e $TOXENV
  else
    tox -e py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
after_success:
  - pip install coveralls
  - coveralls
